version: '3.8'
services:
  crowler_db:
    container_name: crowler_db
    image: postgres:alpine3.19
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DOCKER_POSTGRES_DB_NAME:-SitesIndex}
      - POSTGRES_USER=${DOCKER_POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${DOCKER_POSTGRES_PASSWORD}
      - CROWLER_DB_USER=${DOCKER_CROWLER_DB_USER:-crowler}
      - CROWLER_DB_PASSWORD=${DOCKER_CROWLER_DB_PASSWORD}
    volumes:
      - crowler_db_data:/var/lib/postgresql/data
      - ./pkg/database/postgresql-setup.sh:/docker-entrypoint-initdb.d/init.sh
      - ./pkg/database/postgresql-setup-v1.4.pgsql:/docker-entrypoint-initdb.d/postgresql-setup-v1.4.pgsql

  crowler_api:
    container_name: crowler_api
    environment:
      - POSTGRES_DB=${DOCKER_POSTGRES_DB_NAME:-SitesIndex}
      - CROWLER_DB_USER=${DOCKER_CROWLER_DB_USER:-crowler}
      - CROWLER_DB_PASSWORD=${DOCKER_CROWLER_DB_PASSWORD}
      - POSTGRES_DB_HOST=${DOCKER_DB_HOST:-crowler_db}
      - POSTGRES_DB_PORT=${DOCKER_DB_PORT:-5432}
      - POSTGRES_SSL_MODE=${DOCKER_POSTGRES_SSL_MODE:-disable}
    platform: ${DOCKER_DEFAULT_PLATFORM:-linux/amd64}
    build:
      context: .
      dockerfile: Dockerfile.searchapi
    ports:
      - "8080:8080"
    volumes:
      - crowler_api_data:/app/data
    user: apiuser
    read_only: true

  crowler_engine:
    container_name: crowler_engine
    environment:
      - SELENIUM_HOST=${DOCKER_SELENIUM_HOST:-crowler_vdi}
      - POSTGRES_DB=${DOCKER_POSTGRES_DB_NAME:-SitesIndex}
      - CROWLER_DB_USER=${DOCKER_CROWLER_DB_USER:-crowler}
      - CROWLER_DB_PASSWORD=${DOCKER_CROWLER_DB_PASSWORD}
      - POSTGRES_DB_HOST=${DOCKER_DB_HOST:-crowler_db}
      - POSTGRES_DB_PORT=${DOCKER_DB_PORT:-5432}
      - POSTGRES_SSL_MODE=${DOCKER_POSTGRES_SSL_MODE:-disable}
    platform: ${DOCKER_DEFAULT_PLATFORM:-linux/amd64}
    build:
      context: .
      dockerfile: Dockerfile.thecrowler
    cap_add:
      - NET_ADMIN
      - NET_RAW
    stdin_open: true # For interactive terminal access (optional)
    tty: true # For interactive terminal access (optional)
    ports:
      - "8081:8081"
    volumes:
      - crowler_engine_data:/app/data
    user: crowler

  crowler_vdi:
    container_name: crowler_vdi
    image: ${DOCKER_SELENIUM_IMAGE:-selenium/standalone-chrome:4.18.1-20240224}
    platform: ${DOCKER_DEFAULT_PLATFORM:-linux/amd64}
    ports:
      - "4442-4444:4442-4444"

volumes:
  crowler_db_data:
  crowler_api_data:
  crowler_engine_data:
